language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
env:
- EMBER_TRY_SCENARIO=default
- EMBER_TRY_SCENARIO=ember-1.13.8
- EMBER_TRY_SCENARIO=ember-release
- EMBER_TRY_SCENARIO=ember-beta
- EMBER_TRY_SCENARIO=ember-canary
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
- npm config set spin false
- npm install -g npm@^2
install:
- npm install -g bower
- npm install
- bower install
script:
- ember try $EMBER_TRY_SCENARIO test
deploy:
  provider: npm
  email: null@ember.theater
  api_key:
    secure: ZbDWEJ2xIZZSjmGQXlS+jJGS9KSXQ7P6fRtrqxQRUrmG2gC4qGEYKnCAMlooGa4OIRuF3uG02GBRIOVvNSFjgkO7bP1t88G6OQQBeiMh3y/Pc3Ds/dl9mUiFD4iXWn8UQDFkZUvt/zpTJkjY/3OPnO2GNpgOKhoYywrAjAQN2+1bdMKHfdxF6yxOe25/1KVd7WKJLwDmZhEsLNt9wJMKaI9gqS+b/+iEbo1lzmf0MdJtxyLGNwM5JsMj+dgIGzd17/uqTziXci9+R7iIE+LUvkUI/2TjWl4p8z3GOcYH5jTk4u8UCAztr6ogWXY/lTVBkpJc8X0msPnT4kscC4HO0Y0m08LTRSre/Z9bLKFjnweOymgvgwNK/r8IF64GCKQcDClawrSF4Wj0I4oIpsSECX4cCxZp9R7EPANVXu9nVfOa02SuNwVzSmEULob/TWdqcKpwzUnvMsALhBoADqYpAQku2qemPC3zQFIJGCPkHPCe2P7LAxv3o03t69aUCa6KbnNxek1mk8kF5tPgdYg9Xe/K0VvhcG1LsKzQZVyR8m6JlFzittXbMqlXJBe+YD78SQ6kLFbK+wHiyq1VZN6BsqxABdeNpPBxamEY+yHK4kShZBeRGOTlAV7/Bu2PL24I8PRIWzMghN8qKBaz2xHFV7RrdY2ACC9sYj4nsG75O/Q=
  on:
    tags: true
    repo: null-null-null/ember-logger-test
